# Create a WordPress container & dependencies

wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80

# Create a database container
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: Password.1

# Create a database orchestration container
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: Password.1
